# Generated by Django 4.2.5 on 2025-04-07 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suiviPresence', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activite',
            name='libelle',
            field=models.CharField(default=' ', max_length=255),
            preserve_default=False,
        ),
    ]
