# Generated by Django 4.2.5 on 2025-04-07 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suiviPresence', '0002_activite_libelle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activite',
            name='code',
            field=models.CharField(max_length=8, unique=True),
        ),
    ]
