# Generated by Django 4.2.5 on 2025-04-12 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('suiviPresence', '0003_alter_activite_code'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='participant',
            managers=[
            ],
        ),
    ]
